// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: afs.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "afs.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace afs {

namespace {

const ::google::protobuf::Descriptor* Request_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Request_reflection_ = NULL;
const ::google::protobuf::Descriptor* Reply_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Reply_reflection_ = NULL;
const ::google::protobuf::Descriptor* Stat_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Stat_reflection_ = NULL;
const ::google::protobuf::Descriptor* Dirent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Dirent_reflection_ = NULL;
const ::google::protobuf::Descriptor* DirentReply_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DirentReply_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_afs_2eproto() {
  protobuf_AddDesc_afs_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "afs.proto");
  GOOGLE_CHECK(file != NULL);
  Request_descriptor_ = file->message_type(0);
  static const int Request_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, name_),
  };
  Request_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Request_descriptor_,
      Request::default_instance_,
      Request_offsets_,
      -1,
      -1,
      -1,
      sizeof(Request),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, _is_default_instance_));
  Reply_descriptor_ = file->message_type(1);
  static const int Reply_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Reply, data_),
  };
  Reply_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Reply_descriptor_,
      Reply::default_instance_,
      Reply_offsets_,
      -1,
      -1,
      -1,
      sizeof(Reply),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Reply, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Reply, _is_default_instance_));
  Stat_descriptor_ = file->message_type(2);
  static const int Stat_offsets_[13] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, dev_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, ino_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, mode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, nlink_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, gid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, rdev_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, a_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, m_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, c_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, block_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, blocks_),
  };
  Stat_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Stat_descriptor_,
      Stat::default_instance_,
      Stat_offsets_,
      -1,
      -1,
      -1,
      sizeof(Stat),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stat, _is_default_instance_));
  Dirent_descriptor_ = file->message_type(3);
  static const int Dirent_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Dirent, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Dirent, reclen_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Dirent, d_type_),
  };
  Dirent_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Dirent_descriptor_,
      Dirent::default_instance_,
      Dirent_offsets_,
      -1,
      -1,
      -1,
      sizeof(Dirent),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Dirent, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Dirent, _is_default_instance_));
  DirentReply_descriptor_ = file->message_type(4);
  static const int DirentReply_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DirentReply, count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DirentReply, dirent_),
  };
  DirentReply_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      DirentReply_descriptor_,
      DirentReply::default_instance_,
      DirentReply_offsets_,
      -1,
      -1,
      -1,
      sizeof(DirentReply),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DirentReply, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DirentReply, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_afs_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Request_descriptor_, &Request::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Reply_descriptor_, &Reply::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Stat_descriptor_, &Stat::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Dirent_descriptor_, &Dirent::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      DirentReply_descriptor_, &DirentReply::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_afs_2eproto() {
  delete Request::default_instance_;
  delete Request_reflection_;
  delete Reply::default_instance_;
  delete Reply_reflection_;
  delete Stat::default_instance_;
  delete Stat_reflection_;
  delete Dirent::default_instance_;
  delete Dirent_reflection_;
  delete DirentReply::default_instance_;
  delete DirentReply_reflection_;
}

void protobuf_AddDesc_afs_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tafs.proto\022\003afs\"\027\n\007Request\022\014\n\004name\030\001 \001("
    "\t\"\025\n\005Reply\022\014\n\004data\030\001 \001(\t\"\307\001\n\004Stat\022\013\n\003dev"
    "\030\001 \001(\005\022\013\n\003ino\030\002 \001(\005\022\014\n\004mode\030\003 \001(\005\022\r\n\005nli"
    "nk\030\004 \001(\005\022\013\n\003uid\030\005 \001(\005\022\013\n\003gid\030\006 \001(\005\022\014\n\004rd"
    "ev\030\007 \001(\005\022\014\n\004size\030\010 \001(\003\022\016\n\006a_time\030\t \001(\003\022\016"
    "\n\006m_time\030\n \001(\003\022\016\n\006c_time\030\013 \001(\003\022\022\n\nblock_"
    "size\030\014 \001(\005\022\016\n\006blocks\030\r \001(\005\"6\n\006Dirent\022\014\n\004"
    "name\030\001 \001(\t\022\016\n\006reclen\030\002 \001(\005\022\016\n\006d_type\030\003 \001"
    "(\005\"9\n\013DirentReply\022\r\n\005count\030\001 \001(\005\022\033\n\006dire"
    "nt\030\002 \003(\0132\013.afs.Dirent2\212\001\n\003AFS\022(\n\010afs_ope"
    "n\022\014.afs.Request\032\n.afs.Reply\"\0000\001\022(\n\013afs_g"
    "etattr\022\014.afs.Request\032\t.afs.Stat\"\000\022/\n\013afs"
    "_readdir\022\014.afs.Request\032\020.afs.DirentReply"
    "\"\000B\017\n\007ex.grpc\242\002\003AFSb\006proto3", 547);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "afs.proto", &protobuf_RegisterTypes);
  Request::default_instance_ = new Request();
  Reply::default_instance_ = new Reply();
  Stat::default_instance_ = new Stat();
  Dirent::default_instance_ = new Dirent();
  DirentReply::default_instance_ = new DirentReply();
  Request::default_instance_->InitAsDefaultInstance();
  Reply::default_instance_->InitAsDefaultInstance();
  Stat::default_instance_->InitAsDefaultInstance();
  Dirent::default_instance_->InitAsDefaultInstance();
  DirentReply::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_afs_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_afs_2eproto {
  StaticDescriptorInitializer_afs_2eproto() {
    protobuf_AddDesc_afs_2eproto();
  }
} static_descriptor_initializer_afs_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int Request::kNameFieldNumber;
#endif  // !_MSC_VER

Request::Request()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:afs.Request)
}

void Request::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Request::Request(const Request& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:afs.Request)
}

void Request::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Request::~Request() {
  // @@protoc_insertion_point(destructor:afs.Request)
  SharedDtor();
}

void Request::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Request::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Request::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Request_descriptor_;
}

const Request& Request::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_afs_2eproto();
  return *default_instance_;
}

Request* Request::default_instance_ = NULL;

Request* Request::New(::google::protobuf::Arena* arena) const {
  Request* n = new Request;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Request::Clear() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:afs.Request)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "afs.Request.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:afs.Request)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:afs.Request)
  return false;
#undef DO_
}

void Request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:afs.Request)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "afs.Request.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // @@protoc_insertion_point(serialize_end:afs.Request)
}

::google::protobuf::uint8* Request::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:afs.Request)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "afs.Request.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:afs.Request)
  return target;
}

int Request::ByteSize() const {
  int total_size = 0;

  // optional string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Request::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Request* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Request>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Request::MergeFrom(const Request& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void Request::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Request::CopyFrom(const Request& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Request::IsInitialized() const {

  return true;
}

void Request::Swap(Request* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Request::InternalSwap(Request* other) {
  name_.Swap(&other->name_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Request::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Request_descriptor_;
  metadata.reflection = Request_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Request

// optional string name = 1;
void Request::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Request::name() const {
  // @@protoc_insertion_point(field_get:afs.Request.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Request::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:afs.Request.name)
}
 void Request::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:afs.Request.name)
}
 void Request::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:afs.Request.name)
}
 ::std::string* Request::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:afs.Request.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Request::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Request::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:afs.Request.name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int Reply::kDataFieldNumber;
#endif  // !_MSC_VER

Reply::Reply()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:afs.Reply)
}

void Reply::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Reply::Reply(const Reply& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:afs.Reply)
}

void Reply::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Reply::~Reply() {
  // @@protoc_insertion_point(destructor:afs.Reply)
  SharedDtor();
}

void Reply::SharedDtor() {
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Reply::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Reply::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Reply_descriptor_;
}

const Reply& Reply::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_afs_2eproto();
  return *default_instance_;
}

Reply* Reply::default_instance_ = NULL;

Reply* Reply::New(::google::protobuf::Arena* arena) const {
  Reply* n = new Reply;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Reply::Clear() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Reply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:afs.Reply)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string data = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_data()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->data().data(), this->data().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "afs.Reply.data"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:afs.Reply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:afs.Reply)
  return false;
#undef DO_
}

void Reply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:afs.Reply)
  // optional string data = 1;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->data().data(), this->data().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "afs.Reply.data");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->data(), output);
  }

  // @@protoc_insertion_point(serialize_end:afs.Reply)
}

::google::protobuf::uint8* Reply::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:afs.Reply)
  // optional string data = 1;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->data().data(), this->data().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "afs.Reply.data");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->data(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:afs.Reply)
  return target;
}

int Reply::ByteSize() const {
  int total_size = 0;

  // optional string data = 1;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->data());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Reply::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Reply* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Reply>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Reply::MergeFrom(const Reply& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
}

void Reply::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Reply::CopyFrom(const Reply& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Reply::IsInitialized() const {

  return true;
}

void Reply::Swap(Reply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Reply::InternalSwap(Reply* other) {
  data_.Swap(&other->data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Reply::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Reply_descriptor_;
  metadata.reflection = Reply_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Reply

// optional string data = 1;
void Reply::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Reply::data() const {
  // @@protoc_insertion_point(field_get:afs.Reply.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Reply::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:afs.Reply.data)
}
 void Reply::set_data(const char* value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:afs.Reply.data)
}
 void Reply::set_data(const char* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:afs.Reply.data)
}
 ::std::string* Reply::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:afs.Reply.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Reply::release_data() {
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Reply::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:afs.Reply.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int Stat::kDevFieldNumber;
const int Stat::kInoFieldNumber;
const int Stat::kModeFieldNumber;
const int Stat::kNlinkFieldNumber;
const int Stat::kUidFieldNumber;
const int Stat::kGidFieldNumber;
const int Stat::kRdevFieldNumber;
const int Stat::kSizeFieldNumber;
const int Stat::kATimeFieldNumber;
const int Stat::kMTimeFieldNumber;
const int Stat::kCTimeFieldNumber;
const int Stat::kBlockSizeFieldNumber;
const int Stat::kBlocksFieldNumber;
#endif  // !_MSC_VER

Stat::Stat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:afs.Stat)
}

void Stat::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Stat::Stat(const Stat& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:afs.Stat)
}

void Stat::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  dev_ = 0;
  ino_ = 0;
  mode_ = 0;
  nlink_ = 0;
  uid_ = 0;
  gid_ = 0;
  rdev_ = 0;
  size_ = GOOGLE_LONGLONG(0);
  a_time_ = GOOGLE_LONGLONG(0);
  m_time_ = GOOGLE_LONGLONG(0);
  c_time_ = GOOGLE_LONGLONG(0);
  block_size_ = 0;
  blocks_ = 0;
}

Stat::~Stat() {
  // @@protoc_insertion_point(destructor:afs.Stat)
  SharedDtor();
}

void Stat::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Stat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Stat::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Stat_descriptor_;
}

const Stat& Stat::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_afs_2eproto();
  return *default_instance_;
}

Stat* Stat::default_instance_ = NULL;

Stat* Stat::New(::google::protobuf::Arena* arena) const {
  Stat* n = new Stat;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Stat::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Stat*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(dev_, size_);
  rdev_ = 0;
  ZR_(block_size_, blocks_);
  a_time_ = GOOGLE_LONGLONG(0);

#undef ZR_HELPER_
#undef ZR_

}

bool Stat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:afs.Stat)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 dev = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dev_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_ino;
        break;
      }

      // optional int32 ino = 2;
      case 2: {
        if (tag == 16) {
         parse_ino:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ino_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_mode;
        break;
      }

      // optional int32 mode = 3;
      case 3: {
        if (tag == 24) {
         parse_mode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_nlink;
        break;
      }

      // optional int32 nlink = 4;
      case 4: {
        if (tag == 32) {
         parse_nlink:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nlink_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_uid;
        break;
      }

      // optional int32 uid = 5;
      case 5: {
        if (tag == 40) {
         parse_uid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &uid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_gid;
        break;
      }

      // optional int32 gid = 6;
      case 6: {
        if (tag == 48) {
         parse_gid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &gid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_rdev;
        break;
      }

      // optional int32 rdev = 7;
      case 7: {
        if (tag == 56) {
         parse_rdev:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rdev_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_size;
        break;
      }

      // optional int64 size = 8;
      case 8: {
        if (tag == 64) {
         parse_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &size_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_a_time;
        break;
      }

      // optional int64 a_time = 9;
      case 9: {
        if (tag == 72) {
         parse_a_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &a_time_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_m_time;
        break;
      }

      // optional int64 m_time = 10;
      case 10: {
        if (tag == 80) {
         parse_m_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &m_time_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_c_time;
        break;
      }

      // optional int64 c_time = 11;
      case 11: {
        if (tag == 88) {
         parse_c_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &c_time_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(96)) goto parse_block_size;
        break;
      }

      // optional int32 block_size = 12;
      case 12: {
        if (tag == 96) {
         parse_block_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &block_size_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(104)) goto parse_blocks;
        break;
      }

      // optional int32 blocks = 13;
      case 13: {
        if (tag == 104) {
         parse_blocks:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &blocks_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:afs.Stat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:afs.Stat)
  return false;
#undef DO_
}

void Stat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:afs.Stat)
  // optional int32 dev = 1;
  if (this->dev() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->dev(), output);
  }

  // optional int32 ino = 2;
  if (this->ino() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->ino(), output);
  }

  // optional int32 mode = 3;
  if (this->mode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->mode(), output);
  }

  // optional int32 nlink = 4;
  if (this->nlink() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->nlink(), output);
  }

  // optional int32 uid = 5;
  if (this->uid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->uid(), output);
  }

  // optional int32 gid = 6;
  if (this->gid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->gid(), output);
  }

  // optional int32 rdev = 7;
  if (this->rdev() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->rdev(), output);
  }

  // optional int64 size = 8;
  if (this->size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->size(), output);
  }

  // optional int64 a_time = 9;
  if (this->a_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(9, this->a_time(), output);
  }

  // optional int64 m_time = 10;
  if (this->m_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(10, this->m_time(), output);
  }

  // optional int64 c_time = 11;
  if (this->c_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(11, this->c_time(), output);
  }

  // optional int32 block_size = 12;
  if (this->block_size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(12, this->block_size(), output);
  }

  // optional int32 blocks = 13;
  if (this->blocks() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(13, this->blocks(), output);
  }

  // @@protoc_insertion_point(serialize_end:afs.Stat)
}

::google::protobuf::uint8* Stat::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:afs.Stat)
  // optional int32 dev = 1;
  if (this->dev() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->dev(), target);
  }

  // optional int32 ino = 2;
  if (this->ino() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->ino(), target);
  }

  // optional int32 mode = 3;
  if (this->mode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->mode(), target);
  }

  // optional int32 nlink = 4;
  if (this->nlink() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->nlink(), target);
  }

  // optional int32 uid = 5;
  if (this->uid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->uid(), target);
  }

  // optional int32 gid = 6;
  if (this->gid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->gid(), target);
  }

  // optional int32 rdev = 7;
  if (this->rdev() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->rdev(), target);
  }

  // optional int64 size = 8;
  if (this->size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->size(), target);
  }

  // optional int64 a_time = 9;
  if (this->a_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(9, this->a_time(), target);
  }

  // optional int64 m_time = 10;
  if (this->m_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(10, this->m_time(), target);
  }

  // optional int64 c_time = 11;
  if (this->c_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(11, this->c_time(), target);
  }

  // optional int32 block_size = 12;
  if (this->block_size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(12, this->block_size(), target);
  }

  // optional int32 blocks = 13;
  if (this->blocks() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(13, this->blocks(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:afs.Stat)
  return target;
}

int Stat::ByteSize() const {
  int total_size = 0;

  // optional int32 dev = 1;
  if (this->dev() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dev());
  }

  // optional int32 ino = 2;
  if (this->ino() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->ino());
  }

  // optional int32 mode = 3;
  if (this->mode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mode());
  }

  // optional int32 nlink = 4;
  if (this->nlink() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->nlink());
  }

  // optional int32 uid = 5;
  if (this->uid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->uid());
  }

  // optional int32 gid = 6;
  if (this->gid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->gid());
  }

  // optional int32 rdev = 7;
  if (this->rdev() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rdev());
  }

  // optional int64 size = 8;
  if (this->size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->size());
  }

  // optional int64 a_time = 9;
  if (this->a_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->a_time());
  }

  // optional int64 m_time = 10;
  if (this->m_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->m_time());
  }

  // optional int64 c_time = 11;
  if (this->c_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->c_time());
  }

  // optional int32 block_size = 12;
  if (this->block_size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->block_size());
  }

  // optional int32 blocks = 13;
  if (this->blocks() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->blocks());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Stat::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Stat* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Stat>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Stat::MergeFrom(const Stat& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.dev() != 0) {
    set_dev(from.dev());
  }
  if (from.ino() != 0) {
    set_ino(from.ino());
  }
  if (from.mode() != 0) {
    set_mode(from.mode());
  }
  if (from.nlink() != 0) {
    set_nlink(from.nlink());
  }
  if (from.uid() != 0) {
    set_uid(from.uid());
  }
  if (from.gid() != 0) {
    set_gid(from.gid());
  }
  if (from.rdev() != 0) {
    set_rdev(from.rdev());
  }
  if (from.size() != 0) {
    set_size(from.size());
  }
  if (from.a_time() != 0) {
    set_a_time(from.a_time());
  }
  if (from.m_time() != 0) {
    set_m_time(from.m_time());
  }
  if (from.c_time() != 0) {
    set_c_time(from.c_time());
  }
  if (from.block_size() != 0) {
    set_block_size(from.block_size());
  }
  if (from.blocks() != 0) {
    set_blocks(from.blocks());
  }
}

void Stat::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Stat::CopyFrom(const Stat& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Stat::IsInitialized() const {

  return true;
}

void Stat::Swap(Stat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Stat::InternalSwap(Stat* other) {
  std::swap(dev_, other->dev_);
  std::swap(ino_, other->ino_);
  std::swap(mode_, other->mode_);
  std::swap(nlink_, other->nlink_);
  std::swap(uid_, other->uid_);
  std::swap(gid_, other->gid_);
  std::swap(rdev_, other->rdev_);
  std::swap(size_, other->size_);
  std::swap(a_time_, other->a_time_);
  std::swap(m_time_, other->m_time_);
  std::swap(c_time_, other->c_time_);
  std::swap(block_size_, other->block_size_);
  std::swap(blocks_, other->blocks_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Stat::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Stat_descriptor_;
  metadata.reflection = Stat_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Stat

// optional int32 dev = 1;
void Stat::clear_dev() {
  dev_ = 0;
}
 ::google::protobuf::int32 Stat::dev() const {
  // @@protoc_insertion_point(field_get:afs.Stat.dev)
  return dev_;
}
 void Stat::set_dev(::google::protobuf::int32 value) {
  
  dev_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.dev)
}

// optional int32 ino = 2;
void Stat::clear_ino() {
  ino_ = 0;
}
 ::google::protobuf::int32 Stat::ino() const {
  // @@protoc_insertion_point(field_get:afs.Stat.ino)
  return ino_;
}
 void Stat::set_ino(::google::protobuf::int32 value) {
  
  ino_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.ino)
}

// optional int32 mode = 3;
void Stat::clear_mode() {
  mode_ = 0;
}
 ::google::protobuf::int32 Stat::mode() const {
  // @@protoc_insertion_point(field_get:afs.Stat.mode)
  return mode_;
}
 void Stat::set_mode(::google::protobuf::int32 value) {
  
  mode_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.mode)
}

// optional int32 nlink = 4;
void Stat::clear_nlink() {
  nlink_ = 0;
}
 ::google::protobuf::int32 Stat::nlink() const {
  // @@protoc_insertion_point(field_get:afs.Stat.nlink)
  return nlink_;
}
 void Stat::set_nlink(::google::protobuf::int32 value) {
  
  nlink_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.nlink)
}

// optional int32 uid = 5;
void Stat::clear_uid() {
  uid_ = 0;
}
 ::google::protobuf::int32 Stat::uid() const {
  // @@protoc_insertion_point(field_get:afs.Stat.uid)
  return uid_;
}
 void Stat::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.uid)
}

// optional int32 gid = 6;
void Stat::clear_gid() {
  gid_ = 0;
}
 ::google::protobuf::int32 Stat::gid() const {
  // @@protoc_insertion_point(field_get:afs.Stat.gid)
  return gid_;
}
 void Stat::set_gid(::google::protobuf::int32 value) {
  
  gid_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.gid)
}

// optional int32 rdev = 7;
void Stat::clear_rdev() {
  rdev_ = 0;
}
 ::google::protobuf::int32 Stat::rdev() const {
  // @@protoc_insertion_point(field_get:afs.Stat.rdev)
  return rdev_;
}
 void Stat::set_rdev(::google::protobuf::int32 value) {
  
  rdev_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.rdev)
}

// optional int64 size = 8;
void Stat::clear_size() {
  size_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 Stat::size() const {
  // @@protoc_insertion_point(field_get:afs.Stat.size)
  return size_;
}
 void Stat::set_size(::google::protobuf::int64 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.size)
}

// optional int64 a_time = 9;
void Stat::clear_a_time() {
  a_time_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 Stat::a_time() const {
  // @@protoc_insertion_point(field_get:afs.Stat.a_time)
  return a_time_;
}
 void Stat::set_a_time(::google::protobuf::int64 value) {
  
  a_time_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.a_time)
}

// optional int64 m_time = 10;
void Stat::clear_m_time() {
  m_time_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 Stat::m_time() const {
  // @@protoc_insertion_point(field_get:afs.Stat.m_time)
  return m_time_;
}
 void Stat::set_m_time(::google::protobuf::int64 value) {
  
  m_time_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.m_time)
}

// optional int64 c_time = 11;
void Stat::clear_c_time() {
  c_time_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 Stat::c_time() const {
  // @@protoc_insertion_point(field_get:afs.Stat.c_time)
  return c_time_;
}
 void Stat::set_c_time(::google::protobuf::int64 value) {
  
  c_time_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.c_time)
}

// optional int32 block_size = 12;
void Stat::clear_block_size() {
  block_size_ = 0;
}
 ::google::protobuf::int32 Stat::block_size() const {
  // @@protoc_insertion_point(field_get:afs.Stat.block_size)
  return block_size_;
}
 void Stat::set_block_size(::google::protobuf::int32 value) {
  
  block_size_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.block_size)
}

// optional int32 blocks = 13;
void Stat::clear_blocks() {
  blocks_ = 0;
}
 ::google::protobuf::int32 Stat::blocks() const {
  // @@protoc_insertion_point(field_get:afs.Stat.blocks)
  return blocks_;
}
 void Stat::set_blocks(::google::protobuf::int32 value) {
  
  blocks_ = value;
  // @@protoc_insertion_point(field_set:afs.Stat.blocks)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int Dirent::kNameFieldNumber;
const int Dirent::kReclenFieldNumber;
const int Dirent::kDTypeFieldNumber;
#endif  // !_MSC_VER

Dirent::Dirent()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:afs.Dirent)
}

void Dirent::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Dirent::Dirent(const Dirent& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:afs.Dirent)
}

void Dirent::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reclen_ = 0;
  d_type_ = 0;
}

Dirent::~Dirent() {
  // @@protoc_insertion_point(destructor:afs.Dirent)
  SharedDtor();
}

void Dirent::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Dirent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Dirent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Dirent_descriptor_;
}

const Dirent& Dirent::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_afs_2eproto();
  return *default_instance_;
}

Dirent* Dirent::default_instance_ = NULL;

Dirent* Dirent::New(::google::protobuf::Arena* arena) const {
  Dirent* n = new Dirent;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Dirent::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Dirent*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(reclen_, d_type_);
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool Dirent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:afs.Dirent)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "afs.Dirent.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_reclen;
        break;
      }

      // optional int32 reclen = 2;
      case 2: {
        if (tag == 16) {
         parse_reclen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reclen_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_d_type;
        break;
      }

      // optional int32 d_type = 3;
      case 3: {
        if (tag == 24) {
         parse_d_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &d_type_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:afs.Dirent)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:afs.Dirent)
  return false;
#undef DO_
}

void Dirent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:afs.Dirent)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "afs.Dirent.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional int32 reclen = 2;
  if (this->reclen() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->reclen(), output);
  }

  // optional int32 d_type = 3;
  if (this->d_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->d_type(), output);
  }

  // @@protoc_insertion_point(serialize_end:afs.Dirent)
}

::google::protobuf::uint8* Dirent::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:afs.Dirent)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "afs.Dirent.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional int32 reclen = 2;
  if (this->reclen() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->reclen(), target);
  }

  // optional int32 d_type = 3;
  if (this->d_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->d_type(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:afs.Dirent)
  return target;
}

int Dirent::ByteSize() const {
  int total_size = 0;

  // optional string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional int32 reclen = 2;
  if (this->reclen() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reclen());
  }

  // optional int32 d_type = 3;
  if (this->d_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->d_type());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Dirent::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Dirent* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Dirent>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Dirent::MergeFrom(const Dirent& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.reclen() != 0) {
    set_reclen(from.reclen());
  }
  if (from.d_type() != 0) {
    set_d_type(from.d_type());
  }
}

void Dirent::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Dirent::CopyFrom(const Dirent& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Dirent::IsInitialized() const {

  return true;
}

void Dirent::Swap(Dirent* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Dirent::InternalSwap(Dirent* other) {
  name_.Swap(&other->name_);
  std::swap(reclen_, other->reclen_);
  std::swap(d_type_, other->d_type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Dirent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Dirent_descriptor_;
  metadata.reflection = Dirent_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Dirent

// optional string name = 1;
void Dirent::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Dirent::name() const {
  // @@protoc_insertion_point(field_get:afs.Dirent.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Dirent::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:afs.Dirent.name)
}
 void Dirent::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:afs.Dirent.name)
}
 void Dirent::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:afs.Dirent.name)
}
 ::std::string* Dirent::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:afs.Dirent.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Dirent::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Dirent::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:afs.Dirent.name)
}

// optional int32 reclen = 2;
void Dirent::clear_reclen() {
  reclen_ = 0;
}
 ::google::protobuf::int32 Dirent::reclen() const {
  // @@protoc_insertion_point(field_get:afs.Dirent.reclen)
  return reclen_;
}
 void Dirent::set_reclen(::google::protobuf::int32 value) {
  
  reclen_ = value;
  // @@protoc_insertion_point(field_set:afs.Dirent.reclen)
}

// optional int32 d_type = 3;
void Dirent::clear_d_type() {
  d_type_ = 0;
}
 ::google::protobuf::int32 Dirent::d_type() const {
  // @@protoc_insertion_point(field_get:afs.Dirent.d_type)
  return d_type_;
}
 void Dirent::set_d_type(::google::protobuf::int32 value) {
  
  d_type_ = value;
  // @@protoc_insertion_point(field_set:afs.Dirent.d_type)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int DirentReply::kCountFieldNumber;
const int DirentReply::kDirentFieldNumber;
#endif  // !_MSC_VER

DirentReply::DirentReply()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:afs.DirentReply)
}

void DirentReply::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

DirentReply::DirentReply(const DirentReply& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:afs.DirentReply)
}

void DirentReply::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  count_ = 0;
}

DirentReply::~DirentReply() {
  // @@protoc_insertion_point(destructor:afs.DirentReply)
  SharedDtor();
}

void DirentReply::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DirentReply::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DirentReply::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DirentReply_descriptor_;
}

const DirentReply& DirentReply::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_afs_2eproto();
  return *default_instance_;
}

DirentReply* DirentReply::default_instance_ = NULL;

DirentReply* DirentReply::New(::google::protobuf::Arena* arena) const {
  DirentReply* n = new DirentReply;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DirentReply::Clear() {
  count_ = 0;
  dirent_.Clear();
}

bool DirentReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:afs.DirentReply)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 count = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &count_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_dirent;
        break;
      }

      // repeated .afs.Dirent dirent = 2;
      case 2: {
        if (tag == 18) {
         parse_dirent:
          DO_(input->IncrementRecursionDepth());
         parse_loop_dirent:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_dirent()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_dirent;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:afs.DirentReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:afs.DirentReply)
  return false;
#undef DO_
}

void DirentReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:afs.DirentReply)
  // optional int32 count = 1;
  if (this->count() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->count(), output);
  }

  // repeated .afs.Dirent dirent = 2;
  for (unsigned int i = 0, n = this->dirent_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->dirent(i), output);
  }

  // @@protoc_insertion_point(serialize_end:afs.DirentReply)
}

::google::protobuf::uint8* DirentReply::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:afs.DirentReply)
  // optional int32 count = 1;
  if (this->count() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->count(), target);
  }

  // repeated .afs.Dirent dirent = 2;
  for (unsigned int i = 0, n = this->dirent_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->dirent(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:afs.DirentReply)
  return target;
}

int DirentReply::ByteSize() const {
  int total_size = 0;

  // optional int32 count = 1;
  if (this->count() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->count());
  }

  // repeated .afs.Dirent dirent = 2;
  total_size += 1 * this->dirent_size();
  for (int i = 0; i < this->dirent_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->dirent(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DirentReply::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const DirentReply* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const DirentReply>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DirentReply::MergeFrom(const DirentReply& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  dirent_.MergeFrom(from.dirent_);
  if (from.count() != 0) {
    set_count(from.count());
  }
}

void DirentReply::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DirentReply::CopyFrom(const DirentReply& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DirentReply::IsInitialized() const {

  return true;
}

void DirentReply::Swap(DirentReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DirentReply::InternalSwap(DirentReply* other) {
  std::swap(count_, other->count_);
  dirent_.UnsafeArenaSwap(&other->dirent_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DirentReply::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DirentReply_descriptor_;
  metadata.reflection = DirentReply_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DirentReply

// optional int32 count = 1;
void DirentReply::clear_count() {
  count_ = 0;
}
 ::google::protobuf::int32 DirentReply::count() const {
  // @@protoc_insertion_point(field_get:afs.DirentReply.count)
  return count_;
}
 void DirentReply::set_count(::google::protobuf::int32 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:afs.DirentReply.count)
}

// repeated .afs.Dirent dirent = 2;
int DirentReply::dirent_size() const {
  return dirent_.size();
}
void DirentReply::clear_dirent() {
  dirent_.Clear();
}
const ::afs::Dirent& DirentReply::dirent(int index) const {
  // @@protoc_insertion_point(field_get:afs.DirentReply.dirent)
  return dirent_.Get(index);
}
::afs::Dirent* DirentReply::mutable_dirent(int index) {
  // @@protoc_insertion_point(field_mutable:afs.DirentReply.dirent)
  return dirent_.Mutable(index);
}
::afs::Dirent* DirentReply::add_dirent() {
  // @@protoc_insertion_point(field_add:afs.DirentReply.dirent)
  return dirent_.Add();
}
::google::protobuf::RepeatedPtrField< ::afs::Dirent >*
DirentReply::mutable_dirent() {
  // @@protoc_insertion_point(field_mutable_list:afs.DirentReply.dirent)
  return &dirent_;
}
const ::google::protobuf::RepeatedPtrField< ::afs::Dirent >&
DirentReply::dirent() const {
  // @@protoc_insertion_point(field_list:afs.DirentReply.dirent)
  return dirent_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace afs

// @@protoc_insertion_point(global_scope)
